use_frameworks!

platform :ios, '8.0'

target 'HZSImageCompression_Example' do
  pod 'HZSImageCompression', :path => '../'

  target 'HZSImageCompression_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
